services:
  # Your Application Service
  expense-tracker:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: expense-tracker-app
    ports:
      - "3000:3000"
    environment:
      # Database Configuration - from .env
      - SPRING_DATASOURCE_URL=${SPRING_DATASOURCE_URL}
      - SPRING_DATASOURCE_USERNAME=${SPRING_DATASOURCE_USERNAME}
      - SPRING_DATASOURCE_PASSWORD=${SPRING_DATASOURCE_PASSWORD}
      - SPRING_DATASOURCE_DRIVER=org.h2.Driver

      # JPA Configuration - from .env
      - SPRING_JPA_HIBERNATE_DDL_AUTO=${SPRING_JPA_HIBERNATE_DDL_AUTO}
      - SPRING_JPA_SHOW_SQL=false

      # H2 Console Configuration - from .env
      - SPRING_H2_CONSOLE_ENABLED=${SPRING_H2_CONSOLE_ENABLED}
      - SPRING_H2_CONSOLE_PATH=${SPRING_H2_CONSOLE_PATH}
      - SPRING_H2_CONSOLE_WEB_ALLOW_OTHERS=true

      # JWT Configuration - from .env
      - JWT_SECRET=${JWT_SECRET}
      - JWT_EXPIRATION=${JWT_EXPIRATION:-604800000}
      - JWT_REFRESH_EXPIRATION=${JWT_REFRESH_EXPIRATION:-604800000}

      # Firebase Configuration - from .env
      - FIREBASE_AUTH_URI=${FIREBASE_AUTH_URI:-https://accounts.google.com/o/oauth2/auth}
      - FIREBASE_STORAGE_BUCKET=${FIREBASE_STORAGE_BUCKET:-firebase-expense-tracker.appspot.com}

      # Spring Configuration - from .env
      - SPRING_PROFILES_ACTIVE=${SPRING_PROFILES_ACTIVE}
      - SPRING_SQL_INIT_MODE=${SPRING_SQL_INIT_MODE}

      # File Upload Configuration - from .env
      - SPRING_SERVLET_MULTIPART_MAX_FILE_SIZE=${SPRING_SERVLET_MULTIPART_MAX_FILE_SIZE}
      - SPRING_SERVLET_MULTIPART_MAX_REQUEST_SIZE=${SPRING_SERVLET_MULTIPART_MAX_REQUEST_SIZE}
      - SPRING_SERVLET_MULTIPART_LOCATION=${SPRING_SERVLET_MULTIPART_LOCATION}

      # JVM Configuration - from .env
      - JAVA_OPTS=${JAVA_OPTS}

      # Logging Configuration - from .env
      - LOGGING_LEVEL_COM_LAVISH_EXPENSETRACKER_CONTROLLER=${LOGGING_LEVEL_COM_LAVISH_EXPENSETRACKER_CONTROLLER}
      - LOGGING_LEVEL_ROOT=${LOGGING_LEVEL_ROOT}
      - LOGGING_FILE_NAME=${LOGGING_FILE_NAME}

      # Other Configuration - from .env
      - TINI_SUBREAPER=${TINI_SUBREAPER}
    volumes:
      - ./uploads:/app/uploads
      - ./logs:/app/logs
    restart: unless-stopped
