services:
  # H2 Database Service
  h2-database:
    image: oscarfonts/h2:2.2.224
    container_name: h2-database
    ports:
      - "9092:9092"  # TCP port for database connections
      - "8082:8082"  # Web console port
    volumes:
      - h2-data:/opt/h2-data
      - ./data:/opt/h2-data/backup  # Mount local data directory for backups
    environment:
      - H2_OPTIONS=-tcp -tcpAllowOthers -tcpPort 9092 -web -webAllowOthers -webPort 8082 -baseDir /opt/h2-data
    networks:
      - app-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8082 || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Your Application Service
  expense-tracker:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: expense-tracker-app
    ports:
      - "3000:3000"
    depends_on:
      h2-database:
        condition: service_healthy
    environment:
      # Database Configuration - from .env
      - SPRING_DATASOURCE_URL=${SPRING_DATASOURCE_URL}
      - SPRING_DATASOURCE_USERNAME=${SPRING_DATASOURCE_USERNAME}
      - SPRING_DATASOURCE_PASSWORD=${SPRING_DATASOURCE_PASSWORD}
      - SPRING_DATASOURCE_DRIVER=org.h2.Driver

      # JPA Configuration - from .env
      - SPRING_JPA_HIBERNATE_DDL_AUTO=${SPRING_JPA_HIBERNATE_DDL_AUTO}
      - SPRING_JPA_SHOW_SQL=false

      # H2 Console Configuration - from .env
      - SPRING_H2_CONSOLE_ENABLED=${SPRING_H2_CONSOLE_ENABLED}
      - SPRING_H2_CONSOLE_PATH=${SPRING_H2_CONSOLE_PATH}
      - SPRING_H2_CONSOLE_WEB_ALLOW_OTHERS=true

      # JWT Configuration - from .env
      - JWT_SECRET=${JWT_SECRET}
      - JWT_EXPIRATION=${JWT_EXPIRATION:-604800000}
      - JWT_REFRESH_EXPIRATION=${JWT_REFRESH_EXPIRATION:-604800000}

      # Firebase Configuration - from .env
      - FIREBASE_TYPE=${FIREBASE_TYPE:-service_account}
      - FIREBASE_PROJECT_ID=${FIREBASE_PROJECT_ID}
      - FIREBASE_PRIVATE_KEY_ID=${FIREBASE_PRIVATE_KEY_ID}
      - FIREBASE_PRIVATE_KEY=${FIREBASE_PRIVATE_KEY}
      - FIREBASE_CLIENT_EMAIL=${FIREBASE_CLIENT_EMAIL}
      - FIREBASE_CLIENT_ID=${FIREBASE_CLIENT_ID}
      - FIREBASE_AUTH_URI=${FIREBASE_AUTH_URI:-https://accounts.google.com/o/oauth2/auth}
      - FIREBASE_STORAGE_BUCKET=${FIREBASE_STORAGE_BUCKET}

      # Spring Configuration - from .env
      - SPRING_PROFILES_ACTIVE=${SPRING_PROFILES_ACTIVE}
      - SPRING_SQL_INIT_MODE=${SPRING_SQL_INIT_MODE}

      # File Upload Configuration - from .env
      - SPRING_SERVLET_MULTIPART_MAX_FILE_SIZE=${SPRING_SERVLET_MULTIPART_MAX_FILE_SIZE}
      - SPRING_SERVLET_MULTIPART_MAX_REQUEST_SIZE=${SPRING_SERVLET_MULTIPART_MAX_REQUEST_SIZE}
      - SPRING_SERVLET_MULTIPART_LOCATION=${SPRING_SERVLET_MULTIPART_LOCATION}

      # JVM Configuration - from .env
      - JAVA_OPTS=${JAVA_OPTS}

      # Logging Configuration - from .env
      - LOGGING_LEVEL_COM_LAVISH_EXPENSETRACKER_CONTROLLER=${LOGGING_LEVEL_COM_LAVISH_EXPENSETRACKER_CONTROLLER}
      - LOGGING_LEVEL_ROOT=${LOGGING_LEVEL_ROOT}
      - LOGGING_FILE_NAME=${LOGGING_FILE_NAME}

      # Other Configuration - from .env
      - TINI_SUBREAPER=${TINI_SUBREAPER}
    volumes:
      - ./uploads:/app/uploads
      - ./logs:/app/logs
    networks:
      - app-network
    restart: unless-stopped

networks:
  app-network:
    driver: bridge

volumes:
  h2-data:
    driver: local
