version: '3.8'

services:
  h2-server:
    image: openjdk:11-jre-slim
    container_name: h2-server
    ports:
      - "9092:9092"  # TCP server port
      - "8082:8082"  # Web console port
    volumes:
      - h2-data:/opt/h2-data
    command: >
      sh -c "
      apt-get update && apt-get install -y wget netcat-openbsd curl &&
      wget -O /tmp/h2.jar https://repo1.maven.org/maven2/com/h2database/h2/2.2.224/h2-2.2.224.jar &&
      java -cp /tmp/h2.jar org.h2.tools.Server
      -tcp -tcpAllowOthers -tcpPort 9092
      -web -webAllowOthers -webPort 8082
      -baseDir /opt/h2-data
      -ifNotExists
      "
    restart: unless-stopped
    networks:
      - expense-network
    healthcheck:
      test: ["CMD-SHELL", "nc -z localhost 9092 && nc -z localhost 8082"]
      interval: 15s
      timeout: 10s
      retries: 5
      start_period: 30s

  app-1:
    build: .
    container_name: expense-tracker-app-1
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - SPRING_DATASOURCE_URL=jdbc:h2:tcp://h2-server:9092//opt/h2-data/expensedb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE;ACCESS_MODE_DATA=rw
      - SERVER_PORT=3000
    ports:
      - "3001:3000"  # Expose to external nginx
    volumes:
      - ../app-uploads:/app/uploads
      - app-logs-1:/app/logs
    depends_on:
      h2-server:
        condition: service_healthy
    restart: unless-stopped
    networks:
      - expense-network
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:3000/actuator/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

  app-2:
    build: .
    container_name: expense-tracker-app-2
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - SPRING_DATASOURCE_URL=jdbc:h2:tcp://h2-server:9092//opt/h2-data/expensedb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE;ACCESS_MODE_DATA=rw
      - SERVER_PORT=3000
    ports:
      - "3002:3000"  # Expose to external nginx
    volumes:
      - ../app-uploads:/app/uploads
      - app-logs-2:/app/logs
    depends_on:
      h2-server:
        condition: service_healthy
    restart: unless-stopped
    networks:
      - expense-network
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:3000/actuator/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

  app-3:
    build: .
    container_name: expense-tracker-app-3
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - SPRING_DATASOURCE_URL=jdbc:h2:tcp://h2-server:9092//opt/h2-data/expensedb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE;ACCESS_MODE_DATA=rw
      - SERVER_PORT=3000
    ports:
      - "3003:3000"  # Expose to external nginx
    volumes:
      - ../app-uploads:/app/uploads
      - app-logs-3:/app/logs
    depends_on:
      h2-server:
        condition: service_healthy
    restart: unless-stopped
    networks:
      - expense-network
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:3000/actuator/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

  nginx:
    image: nginx:alpine
    container_name: expense-tracker-nginx
    ports:
      - "80:80"  # Main entry point
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ../app-uploads:/app/uploads  # Mount uploads volume for direct file serving
    depends_on:
      - app-1
      - app-2
      - app-3
    restart: unless-stopped
    networks:
      - expense-network
    healthcheck:
      test: ["CMD-SHELL", "wget --no-verbose --tries=1 --spider http://localhost/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

volumes:
  h2-data:
  ../app-uploads:
  app-logs-1:
  app-logs-2:
  app-logs-3:

networks:
  expense-network:
    driver: bridge
