version: '3.8'

services:
  expense-tracker:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - FIREBASE_PROJECT_ID=simple-expense-manager-1993
      - FIREBASE_PRIVATE_KEY_ID=6b67cb4a4165226441477cf07768b1cb88e39796
      - FIREBASE_PRIVATE_KEY="-----BEGIN PRIVATE KEY-----\nMIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQChIk+UGck2GTUi\nVZ4Ojw1W2O4SuVKYvF5LCus2hUKhrpn+ph71aMA+iq41Udg9qOYa+PQwnjBTW7mV\nsRHp5BmzL+/bxFsBgC0gFo+2kEgzUt6R0eYNoRlVruvmex3C1LOTYijMYcBFCI63\n7XEsy5edHq/wITtJSrrJB4olO7eFp8xy06lLIruei39ucVBY6lU7x4rtF1XJ+MCy\nL6YujfHiOJPhwCGNBp3pkIf7/mj+F/jwZWNiLhO4jij2n6+hhLfnZj9gwffVm1Iy\nQSO5SPDZT5Y75dKC8OK5CpUjHABladzEy7Gd9ZfDUQ6xR9+hQ1QKjdP0Y5Hmfko5\nmZm4Zgl1AgMBAAECggIACl7XhtAIYGw2ZyeMqjdgPnzsiPV29gAM7zZRxZrwMHuO\nNd1cruLnQ+SFNPF3zJ4fHdDJ1zWIetueLIlufk0RL18QMvwmoZ3YKabHaJKi0Z94\nK3k6HcScHrozkgxN8cu35AOEXdppDLhchm9od4osj5mZmAeXgHkoCjIAnN1Z9ibT\nTmK0VywnTn7o8obygYRzYeSd06WCLHTbPXdIVEqTagGAL5Y7R1Gocghe9uUyts0\nO6nAw1IFCAaNkZTQb1ZIMLjS15Ia6Y+8FDVqNgfizteaWKqpvbBR8d8/ePBS+W3R\n9CepsZesD+C9GG/svmc7ZzxSTbgLSp48mVwr9GAEuQKBgQDPQ6OCoYxh7+DSQkjW\n0i/CALOdbxKbrhzOmjYHGCV9wAuPalQPmQOTm2AQB7icT6HqscbgXsFwsWDwIFrL\n/itmNPMIW6n1z7AXs+tBzIB5uQcnxLybWOeWm4TLPn4p6u9wvsBd/ejppctrBYH/\nzzjbxG09ZHna94jw77opp2epCQKBgQDHBdhW0fBPNraQ0oUullCCXhKf56zx3jaH\nY+A+Z0XM5dYnSLfuEfVwEpzkNjjnNqCOTkdpOCEttbnX01PYF5Lny/21XrDPTwUx\nFE82C1ixY1rI7tZ8W9OYgbIS77h7gkO2w5plOdmRHbDf/AyH3vMo/CSXrxK3qsXK\n2ayy+6/UDQKBgQDJW0fd3/5XI0lCW50R/m7hRfc5irAESLm5yb2VVNMPgOR6Nu1l\nnd0IqNlBmY6zZPXD4WR5k/TP+7NWnchgCBS3nddCFnNe2J+V13hFm1xxZN1buFkX\nft62xW3UWmkNZi2qVdbjOYrueuDNnzM1h2cQspsCGrv7i6IhmHQ+hWFCqQKBgQC0\nN0a+1zuTfyex2+9dUB927VhQE6k3GtClqHoWBw3djAFvcRmcKgblhPUscSz1sTGR\nqrBfRsREb9no5SN2+WG9I6qJIUVZc2RwHMPdXEjj1+PNLvhpg30HC+oD265hqINI\na7bTEp9AGHKhX8q4/dmRs0BP8ygvyCNym8kWCXIdwQKBgGfazu+qZkWzeCUdy7bu\nIHg6sv84Iizx6JJrlVCmeilp2RAtYfKynx4x3A1NBFPwVMOJrYsOkrwLKSavGQm4\njDcA/+Sdo4pD60r3w3O7M2TYf6gIvbz5TqZTMFG2nYQhwxeqdFaAJkb0uj0MCBOj\n/OevnOIiX6Que6F6iQvqoFBY\n-----END PRIVATE KEY-----\n"
      - FIREBASE_CLIENT_EMAIL=firebase-adminsdk-gcx0f@simple-expense-manager-1993.iam.gserviceaccount.com
      - FIREBASE_CLIENT_ID=116407173136789687017

      - SPRING_PROFILES_ACTIVE=prod
      # Database configuration for persistent storage
      - SPRING_DATASOURCE_URL=jdbc:h2:file:/h2-data/expensedb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
      - SPRING_DATASOURCE_USERNAME=sa
      - SPRING_DATASOURCE_PASSWORD=
      - SPRING_H2_CONSOLE_ENABLED=true
      - SPRING_H2_CONSOLE_PATH=/h2-console
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - SPRING_SQL_INIT_MODE=always
    volumes:
      - ./data/h2:/h2-data
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 1
      start_period: 60s
