services:
  expense-tracker:
    build: 
      context: .
      dockerfile: Dockerfile
    image: expense-tracker:latest
    container_name: expense-tracker
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      # Use in-memory database to avoid file permission issues
      - SPRING_DATASOURCE_URL=jdbc:h2:mem:expensedb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
      - SPRING_DATASOURCE_USERNAME=sa
      - SPRING_DATASOURCE_PASSWORD=
      - SPRING_H2_CONSOLE_ENABLED=true
      - SPRING_H2_CONSOLE_PATH=/h2-console
      - SPRING_JPA_HIBERNATE_DDL_AUTO=create-drop
      - SPRING_SQL_INIT_MODE=always
      # Optimized JVM settings for Raspberry Pi
      - JAVA_OPTS=-Xms128m -Xmx384m -XX:+UseG1GC -XX:G1HeapRegionSize=8m
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/actuator/health"]
      interval: 45s
      timeout: 15s
      retries: 3
      start_period: 60s
    # Resource limits compatible with older docker-compose
    mem_limit: 512m
    cpus: 0.8

volumes:
  gradle-cache:
    driver: local
