version: '3.8'

services:
  expense-tracker:
    image: expense-tracker:latest
    container_name: expense-tracker
    platform: linux/arm64
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - SPRING_DATASOURCE_URL=jdbc:h2:tcp://host.docker.internal:9092//var/lib/h2-data/expensedb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE;ACCESS_MODE_DATA=rw;
      - SPRING_DATASOURCE_USERNAME=sa
      - SPRING_DATASOURCE_PASSWORD=
      - SPRING_H2_CONSOLE_ENABLED=true
      - SPRING_H2_CONSOLE_PATH=/h2-console
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - SPRING_SQL_INIT_MODE=always
      - JAVA_OPTS=-Xms128m -Xmx384m -XX:+UseG1GC -XX:G1HeapRegionSize=8m
      - LOGGING_LEVEL_COM_LAVISH_EXPENSETRACKER_CONTROLLER=DEBUG
      - LOGGING_LEVEL_ROOT=INFO
      - LOGGING_FILE_NAME=/app/logs/expense-tracker.log
      - TINI_SUBREAPER=1
    volumes:
      - h2-data:/app/h2-data
      - ./logs:/app/logs:rw
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    deploy:
      resources:
        limits:
          cpus: '0.9'
          memory: 512M
    security_opt:
      - no-new-privileges:true
    init: true
    extra_hosts:
      - "host.docker.internal:host-gateway"

volumes:
  h2-data:
    driver: local
  gradle-cache:
    driver: local
