version: '3.8'

services:
  h2-database:
    build:
      context: .
      dockerfile: Dockerfile.h2
    container_name: h2
    ports:
      - "9092:9092"  # TCP port for database connections
      - "8082:8082"  # Web console port
    volumes:
      - ~/Desktop/h2-data:/opt/h2-data  # Direct mapping to local directory
      - ~/Desktop/h2-backup:/opt/h2-data/backup  # Local backup directory
    environment:
      - JAVA_OPTS=-Xms64m -Xmx256m  # Optimized for Raspberry Pi
      - H2_DATABASE_URL=jdbc:h2:tcp://localhost:9092//opt/h2-data/expensedb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE;ACCESS_MODE_DATA=rw
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8082 || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    networks:
      - h2-network

networks:
  h2-network:
    driver: bridge
